import type { Rule } from './rules.js'

/**
 * 内置规则集：精选高风险行为，默认 deny（git 危险操作部分 warn）。
 * 不可删除、不可改 pattern；可经 builtins.overrides 启停/覆盖动作。
 */
export const BUILTIN_RULES: Rule[] = [
  {
    id: 'rm-root',
    tools: ['bash'],
    pattern: '\\brm\\s+(?:-[a-zA-Z]+\\s+)+\\\\?["\']?[~/]\\\\?["\']?(?:\\s|[;"\'&|\\\\]|$)',
    action: 'deny',
    reason: '禁止删除根目录或家目录（{pattern}）',
    enabled: true,
    builtin: true,
  },
  {
    id: 'curl-pipe-sh',
    tools: ['bash'],
    pattern: '\\b(curl|wget)\\b[^;|&]{0,200}\\|\\s*(sh|bash)\\b',
    action: 'deny',
    reason: '禁止通过管道直接执行远程下载的脚本（{pattern}）',
    enabled: true,
    builtin: true,
  },
  {
    id: 'iwr-iex',
    tools: ['bash'],
    pattern: '\\biwr\\b[^;|&]{0,200}\\|\\s*iex\\b',
    action: 'deny',
    reason: '禁止 PowerShell 远程脚本执行（Invoke-Expression）（{pattern}）',
    enabled: true,
    builtin: true,
  },
  {
    id: 'force-push-main',
    tools: ['bash'],
    pattern: '\\bgit\\s+push[^;|&]*?(--force|-f)[^;|&]*\\s(branch\\s+)?(main|master)\\b',
    action: 'deny',
    reason: '禁止对主分支（main/master）强推（{pattern}）',
    enabled: true,
    builtin: true,
  },
  {
    id: 'git-reset-hard',
    tools: ['bash'],
    pattern: '\\bgit\\s+reset\\s+--hard\\b',
    action: 'warn',
    reason: 'git reset --hard 会丢弃未提交改动，请确认（{pattern}）',
    enabled: true,
    builtin: true,
  },
  {
    id: 'sudo-rm-root',
    tools: ['bash'],
    pattern: '\\bsudo\\s+rm\\s+(?:-[a-zA-Z]+\\s+)*\\\\?["\']?[~/]\\\\?["\']?(?:\\s|[;"\'&|\\\\]|$)',
    action: 'deny',
    reason: '禁止提权删除根目录或家目录（{pattern}）',
    enabled: true,
    builtin: true,
  },
  {
    id: 'fork-bomb',
    tools: ['bash'],
    pattern: ':\\s*\\(\\s*\\)\\s*\\{\\s*:\\s*\\|',
    action: 'deny',
    reason: '检测到 fork bomb 模式（{pattern}）',
    enabled: true,
    builtin: true,
  },
  {
    id: 'chmod-root',
    tools: ['bash'],
    pattern: '\\bchmod\\s+(-R\\s+)?777\\s+\\\\?["\']?[~/]\\\\?["\']?(?:\\s|[;"\'&|\\\\]|$)',
    action: 'deny',
    reason: '禁止对根目录或家目录 777 授权（{pattern}）',
    enabled: true,
    builtin: true,
  },
  {
    id: 'shutdown',
    tools: ['bash'],
    pattern: '\\b(shutdown|reboot|poweroff|init\\s+0)\\b',
    action: 'deny',
    reason: '禁止关机/重启类系统操作（{pattern}）',
    enabled: true,
    builtin: true,
  },
  {
    id: 'mkfs',
    tools: ['bash'],
    pattern: '\\bmkfs(\\.[a-z0-9]+)?\\b',
    action: 'deny',
    reason: '禁止格式化磁盘（{pattern}）',
    enabled: true,
    builtin: true,
  },
  {
    id: 'dd-disk',
    tools: ['bash'],
    pattern: '\\bdd\\s+if=/dev/zero\\s+of=/dev/sd',
    action: 'deny',
    reason: '禁止向磁盘设备写入零数据（{pattern}）',
    enabled: true,
    builtin: true,
  },
]
